component_depth: 1
languages:
- java
exclude:
- ./at/.*
- ./at/bestsolution/.*
- ./at/bestsolution/drawswf/.*
- ./at/bestsolution/drawswf/actions/.*
- ./at/bestsolution/drawswf/dialog/.*
- ./at/bestsolution/drawswf/drawobjects/.*
- ./at/bestsolution/drawswf/images/.*
- ./at/bestsolution/drawswf/images/16x16/.*
- ./at/bestsolution/drawswf/images/24x24/.*
- ./at/bestsolution/drawswf/menu/.*
- ./at/bestsolution/drawswf/plugin/.*
- ./at/bestsolution/drawswf/plugin/remotesave/.*
- ./at/bestsolution/drawswf/plugin/remotesave/action/.*
- ./at/bestsolution/drawswf/plugin/remotesave/dialog/.*
- ./at/bestsolution/drawswf/plugin/remotesave/util/.*
- ./at/bestsolution/drawswf/toolbar/.*
- ./at/bestsolution/drawswf/util/.*
- ./at/bestsolution/ext/.*
- ./at/bestsolution/ext/awt/.*
- ./at/bestsolution/ext/swing/.*
- ./at/bestsolution/ext/swing/dialog/.*
- ./at/bestsolution/ext/swing/icon/.*
- ./at/bestsolution/util/.*
- ./com/.*
- ./com/anotherbigidea/.*
- ./com/anotherbigidea/flash/.*
- ./com/anotherbigidea/flash/interfaces/.*
- ./com/anotherbigidea/flash/movie/.*
- ./com/anotherbigidea/flash/readers/.*
- ./com/anotherbigidea/flash/sound/.*
- ./com/anotherbigidea/flash/structs/.*
- ./com/anotherbigidea/flash/writers/.*
- ./com/anotherbigidea/io/.*
- ./com/anotherbigidea/util/.*
- ./com/incors/.*
- ./com/incors/plaf/.*
- ./com/incors/plaf/kunststoff/.*
- ./com/incors/plaf/kunststoff/icons/.*
- ./com/incors/plaf/kunststoff/themes/.*
- ./lib/.*
- ./org/.*
- ./org/apache/.*
- ./org/apache/batik/.*
- ./org/apache/batik/ext/.*
- ./org/apache/batik/ext/awt/.*
- ./org/apache/batik/ext/awt/image/.*
- ./org/apache/batik/ext/awt/image/renderable/.*
- ./org/apache/batik/ext/awt/image/rendered/.*
- ./org/apache/batik/util/.*
